name: Build ESP32 Project

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install ESP-IDF dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build ccache libffi-dev libssl-dev dfu-util

    - name: Clone ESP-IDF
      run: |
        git clone --recursive https://github.com/espressif/esp-idf.git
        cd esp-idf
        ./install.sh esp32
        echo "source $GITHUB_WORKSPACE/esp-idf/export.sh" >> $GITHUB_ENV

    - name: Build Project
      run: |
        source $GITHUB_WORKSPACE/esp-idf/export.sh
        idf.py set-target esp32
        idf.py build
      working-directory: ./src  # adjust to where your main project folder is
